resource_group_name  = "cmaz-7850b25e-mod3-rg"
storage_account_name = "cmaz7850b25esa"
vnet_name            = "cmaz-7850b25e-mod3-vnet"
frontend_subnet_name = "frontend"
backend_subnet_name  = "backend"
email                = "bandari_shashank@epam.com"